### PR TITLE
updater example

### PR DESCRIPTION
**Pull request by cbouss**
Add command `percy recipe patch <patch_file>` which takes a patch file such as:
```
[
    { "op": "add_or_replace", "section": "host", "package": "openssl", "constraint": ["{{ openssl }}"] },
    { "op": "add_or_replace", "section": "run", "package": "openssl", "constraint": ["3.*"] },
    { "op": "replace", "section": "host", "package": "numpy", "constraint": ["1.21  # [py<311]", "1.23  # [py>=311]"] },
    { "op": "replace", "section": "run", "package": "numpy", "constraint": [">=1.21,<=2.0a0  # [py<311]", ">=1.23,<=2.0a0  # [py>=311]"] },
    { "op": "remove", "section": "host", "package": "geos", "constraint": [] },
    { "op": "remove", "section": "run", "package": "geos", "constraint": [] },
    { "op": "add", "section": "host", "package": "geos2", "constraint": ["1.2.3"] },
    { "op": "add", "section": "run", "package": "{{ pin_compatible('geos2') }}", "constraint": [""] }
]
```

This can also be called through a rendered recipe: `recipe.patch(op_list)`

Examples have been added to `examples/patch`. updater.py uses percy, while updater_standalone.py is an example of the same using ruamel only.

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
I found a small bug. If I run `python percy/examples/patch/updater.py` then in the requirements/run will be added a blank line
Screenshot 2023-06-13 at 11 05 12

**Comment by skupr-anaconda** [comment]
It would be nice to add more functionality to patch a recipe:
"noarch", "script", "requires", "commands".

**Comment by cbouss** [comment]
Thank you @skupr-anaconda , I addressed your comments and modified the patch syntax to be more flexible.

You can write something like this:
```
[
    {
        "op": "remove",
        "path": "@output/build/noarch"
    },
    {
        "op": "add",
        "path": "@output/build/skip",
        "value": "True  # [py<37]"
    },
    {
        "op": "replace",
        "path": "@output/build/script",
        "match": "\\bpip install\\b(?!=.*--no-build-isolation)",
        "value": "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv"
    },
    {
        "op": "add",
        "path": "@output/requirements/host",
        "match": "\\bpython\\b",
        "value": ["python"]
    },
    {
        "op": "add",
        "path": "@output/requirements/run",
        "match": "\\bpython\\b",
        "value": ["python"]
    },
    {
        "op": "add",
        "path": "@output/requirements/host",
        "match": "\\bsetuptools\\b",
        "value": ["setuptools"]
    },
    {
        "op": "add",
        "path": "@output/requirements/host",
        "match": "\\bwheel\\b",
        "value": ["wheel"]
    },
    {
        "op": "add",
        "path": "@output/test/requires",
        "match": "\\bpip\\b",
        "value": ["pip"]
    },
    {
        "op": "add",
        "path": "@output/test/commands",
        "match": "\\bpip check\\b",
        "value": ["pip check"]
    }
]
```

`path` is a full path, `@output` being a placeholder.
`match` is a regex pattern to match the value at path.
`value` is a list of replacement values.

One thing missing is how to preserve selectors. 
For example, to allow replacing `openssl #[win]` by `openssl {{openssl}} #[win]`.

**Comment by skupr-anaconda** [comment]
> [
>     {
>         "op": "remove",
>         "path": "@output/build/noarch"
>     },
>     {
>         "op": "add",
>         "path": "@output/build/skip",
>         "value": "True  # [py<37]"
>     },
>     {
>         "op": "replace",
>         "path": "@output/build/script",
>         "match": "\\bpip install\\b(?!=.*--no-build-isolation)",
>         "value": "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv"
>     },
>     {
>         "op": "add",
>         "path": "@output/requirements/host",
>         "match": "\\bpython\\b",
>         "value": ["python"]
>     },
>     {
>         "op": "add",
>         "path": "@output/requirements/run",
>         "match": "\\bpython\\b",
>         "value": ["python"]
>     },
>     {
>         "op": "add",
>         "path": "@output/requirements/host",
>         "match": "\\bsetuptools\\b",
>         "value": ["setuptools"]
>     },
>     {
>         "op": "add",
>         "path": "@output/requirements/host",
>         "match": "\\bwheel\\b",
>         "value": ["wheel"]
>     },
>     {
>         "op": "add",
>         "path": "@output/test/requires",
>         "match": "\\bpip\\b",
>         "value": ["pip"]
>     },
>     {
>         "op": "add",
>         "path": "@output/test/commands",
>         "match": "\\bpip check\\b",
>         "value": ["pip check"]
>     }
> ]

```
jsonschema.exceptions.ValidationError: 'True  # [py<37]' is not of type 'array'

Failed validating 'type' in schema['items']['properties']['value']:
    {'items': {'type': 'string'}, 'type': 'array'}

On instance[1]['value']:
    'True  # [py<37]'
```

**Comment by cbouss** [comment]
> > [
> > {
> > "op": "remove",
> > "path": "@output/build/noarch"
> > },
> > {
> > "op": "add",
> > "path": "@output/build/skip",
> > "value": "True  # [py<37]"
> > },
> > {
> > "op": "replace",
> > "path": "@output/build/script",
> > "match": "\bpip install\b(?!=.*--no-build-isolation)",
> > "value": "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv"
> > },
> > {
> > "op": "add",
> > "path": "@output/requirements/host",
> > "match": "\bpython\b",
> > "value": ["python"]
> > },
> > {
> > "op": "add",
> > "path": "@output/requirements/run",
> > "match": "\bpython\b",
> > "value": ["python"]
> > },
> > {
> > "op": "add",
> > "path": "@output/requirements/host",
> > "match": "\bsetuptools\b",
> > "value": ["setuptools"]
> > },
> > {
> > "op": "add",
> > "path": "@output/requirements/host",
> > "match": "\bwheel\b",
> > "value": ["wheel"]
> > },
> > {
> > "op": "add",
> > "path": "@output/test/requires",
> > "match": "\bpip\b",
> > "value": ["pip"]
> > },
> > {
> > "op": "add",
> > "path": "@output/test/commands",
> > "match": "\bpip check\b",
> > "value": ["pip check"]
> > }
> > ]
> 
> ```
> jsonschema.exceptions.ValidationError: 'True  # [py<37]' is not of type 'array'
> 
> Failed validating 'type' in schema['items']['properties']['value']:
>     {'items': {'type': 'string'}, 'type': 'array'}
> 
> On instance[1]['value']:
>     'True  # [py<37]'
> ```

My bad, value has to be an array.
```
[
    {
        "op": "remove",
        "path": "@output/build/noarch"
    },
    {
        "op": "add",
        "path": "@output/build/skip",
        "value": ["True  # [py<37]"]
    },
    {
        "op": "replace",
        "path": "@output/build/script",
        "match": "\\bpip install\\b(?!=.*--no-build-isolation)",
        "value": ["{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv"]
    },
    {
        "op": "add",
        "path": "@output/requirements/host",
        "match": "\\bpython\\b",
        "value": ["python"]
    },
    {
        "op": "add",
        "path": "@output/requirements/run",
        "match": "\\bpython\\b",
        "value": ["python"]
    },
    {
        "op": "add",
        "path": "@output/requirements/host",
        "match": "\\bsetuptools\\b",
        "value": ["setuptools"]
    },
    {
        "op": "add",
        "path": "@output/requirements/host",
        "match": "\\bwheel\\b",
        "value": ["wheel"]
    },
    {
        "op": "add",
        "path": "@output/test/requires",
        "match": "\\bpip\\b",
        "value": ["pip"]
    },
    {
        "op": "add",
        "path": "@output/test/commands",
        "match": "\\bpip check\\b",
        "value": ["pip check"]
    }
]
```

**Comment by cbouss** [comment]
Latest changes:
- selectors are preserved (unless captured as part of the match pattern)
- value accepts string or array

**Review by JeanChristopheMorinPerso — APPROVED** [review]

**Pull request merged**
